ports:
- port: 8080
  onOpen: open-preview

tasks:
  - init: gradle build -x test
    command: gradle runBoot

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-gradle
    - pivotal.vscode-spring-boot
    - DavidAnson.vscode-markdownlint
    - Gruntfuggly.todo-tree
    - shardulm94.trailing-spaces
    - eamodio.gitlens
