version: "3.9"

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_DATABASE: ludus
      MARIADB_USER: ludus
      MARIADB_PASSWORD: ludus
      MARIADB_ROOT_PASSWORD: toor
  ludus:
    depends_on:
      - database
    image: colosseum-project/ludus:latest
    ports:
      - 8081:8081
    restart: always
    environment:
      DB_URL: jdbc:mariadb://database:3306/ludus
      DB_USERNAME: ludus
      DB_PASSWORD: ludus

volumes:
  data:
