---
server:
  port: 8081
spring:
  application:
    name: ludus
  profiles:
    default: production
    group:
      development:
        - debugmode
        - devdb
      test:
        - testdb
      production:
        - proddb
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org:
      springframework: INFO
arena:
  endpoint: ${ARENA_ENDPOINT:http://localhost:8082}
